### PR TITLE
feat:Exposing more props to renderPane for EditorTab（invalid）

### LINKED ISSUE #649: feat:Exposing more props to renderPane for EditorTab
I also have a suggestion on custom editor tab [group.tsx](https://github.com/DTStack/molecule/blob/ec0d4591ac8b3209571446a94e35eab67fbfc7ca/src/workbench/editor/group.tsx#L117). Exposing more props to renderPane would be great for customizing, for example `tab.renderPane({...tab.data, tabId: tab?.id, groupId: id})`.

_Originally posted by @hepezu in https://github.com/DTStack/molecule/issues/644#issuecomment-1024910401_

### PR DESCRIPTION
**Pull request by Zaoei**
## Description

exposing more props to renderPane for EditorTab

Fixes #649

## Changes

-   tab.renderPane method arguments add tab and group
-   add renderPane example

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mumiao** [comment]
#757

**Review by wewoor — APPROVED** [review]
+1

**Review by wewoor — APPROVED** [review]
+1

**Comment by mumiao** [comment]
+1

**Comment by Zaoei** [comment]
@mortalYoung 我解决了冲突之后提交，就没有走 codecov。要不关闭这个 pr，我重新提一个？

**Comment by Zaoei** [comment]
@mortalYoung @mumiao @wewoor 
由于没有走 codecov，关闭这个 PR。
改用 #759

**Pull request closed without merging**
